plugins {
    id 'com.android.application'
}

android {
    namespace 'com.shahriyarshehab.cinebox'
    compileSdk 34

    defaultConfig {
        applicationId "com.shahriyarshehab.cinebox"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "2.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        resValue "string", "web_app_url", "https://shahriyarshehab.github.io/cinebox/"
        resValue "string", "web_app_host", "shahriyarshehab.github.io"
        resValue "string", "web_app_path", "/cinebox/"
    }

    signingConfigs {
        release {
            storeFile file('../cinebox-release-key.jks')
            storePassword 'cinebox2026'
            keyAlias 'cinebox'
            keyPassword 'cinebox2026'
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'androidx.media3:media3-exoplayer:1.3.1'
    implementation 'androidx.media3:media3-ui:1.3.1'
    implementation 'androidx.media3:media3-datasource-okhttp:1.3.1'
    implementation 'androidx.media3:media3-common:1.3.1'
}
