plugins {
    id 'com.android.application'
}

android {
    namespace 'com.shahriyarshehab.cinebox'
    compileSdk 34

    defaultConfig {
        applicationId "com.shahriyarshehab.cinebox"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        resValue "string", "web_app_url", "https://shahriyarshehab.github.io/cinebox/"
        resValue "string", "web_app_host", "shahriyarshehab.github.io"
        resValue "string", "web_app_path", "/cinebox/"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
    implementation 'androidx.browser:browser:1.8.0'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.12.0'
}
